### ISSUE TITLE
Differences with zetteldeft

### ISSUE THREAD

**Issue by AtomicNess123** [ymherklotz/emacs-zettelkasten#4]
What are the main differences with Zetteldeft and why would you recommend your package?

**Comment by ymherklotz** [comment]
For `zettelkasten.el`, the main difference is no dependency on `deft`, which can be a good or bad thing.  I just wanted my own tiny implementation to adapt it to my workflow, so that is the main motivation for it.  If you are therefore comfortable with lisp, this should provide a simple base to work on and add more features.

`org-zettelkasten` is a completely different way of handling notes, using `org-mode` heavily, and following closely with the original idea of a Zettelkasten.  It is therefore a bit more manual, but is what I am currently using.  The main idea is to nest notes to link them, but also provide IDs to link notes.  More info can be found in this [blog post](https://yannherklotz.com/blog/2020-12-21-introduction-to-luhmanns-zettelkasten.html).

**Comment by AtomicNess123** [comment]
Sorry to reopen: I noticed that your system implies creating categories. The point of notes one would assume is avoiding categories all together since all notes are a network without categories, just tags identifying each note. Also I see that the difference with other methods is that in yours the notes are creates within that specific category in mind, so before creating the note one must think where it belongs to. Correct me if I am wrong. Thanks!

**Comment by ymherklotz** [comment]
I actually wouldn't think of them as categories, they are basically just long notes, where you can add things in between.  If you have a new idea which doesn't really fit into your notes, you just create a new top-level note, but you should always just try to make it a continuation to an existing note. This is how the original Zettelkasten by Luhmann also worked, and which existing systems don't focus on anymore.  This was another reason for working on this.

This gives some default ordering to the notes, which might not be the best, and so can easily be edited using links and their unique IDs.  This is closer to Luhmann's own idea, and provides a base structure for the notes, but this structure can always be enhanced by providing more links, which creates links between notes.

I think every article about Luhmann's Zettelkasten creates it's own version of it, and makes assumptions, so I like to just look at a more unbiased article about it (https://niklas-luhmann-archiv.de/nachlass/zettelkasten), where they categorized everyone of his notes and just described it's general structure.  This is the structure I follow and it now makes more sense to me than just completely unstructured notes.

**Comment by AtomicNess123** [comment]
Thanks. In my own case, most of the times I couldn't know in which category to put my notes, because the topics I work with are interdisciplinary (computational biology... does it belong to computing or biology? To put a blunt example). Maybe in your work it's more convenient. Thus, there is no one-fits-all! :)
